[package]
name = "pit"
version = "0.1.0"
authors = ["Jack Bass <jeb4571@rit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
difference = "2.0.0"